name: Shortly

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: fetch code 
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test
